# Generated by Django 4.2.7 on 2024-01-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('is_data_upload', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=100, null=True)),
                ('doctor_phone', models.CharField(max_length=100, null=True)),
                ('doctor_mail', models.CharField(max_length=100, null=True)),
                ('doctor_password', models.CharField(max_length=100, null=True)),
                ('special_treat_patients', models.ManyToManyField(to='user.patient')),
            ],
        ),
    ]
