# Generated by Django 4.2.7 on 2024-01-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slices',
            fields=[
                ('slices_id', models.AutoField(primary_key=True, serialize=False)),
                ('slices_position', models.CharField(max_length=100, null=True)),
                ('result', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='teeth_slices',
            field=models.ManyToManyField(to='user.slices'),
        ),
    ]
