# Generated by Django 4.2.7 on 2024-01-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_slices_doctor_is_admin_patient_teeth_slices'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('code_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=100, null=True)),
                ('expire_time', models.TimeField(default=None, null=True)),
            ],
        ),
    ]
