# Generated by Django 4.2.7 on 2024-01-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_invitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='expire_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
