# Generated by Django 4.2.7 on 2024-01-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_invitecode_expire_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='left_lower_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='left_upper_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='right_lower_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='right_upper_upload',
            field=models.BooleanField(default=False),
        ),
    ]
