# Generated by Django 4.0.6 on 2024-03-10 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_patient_left_lower_upload_patient_left_upper_upload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='left_lower_upload',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='left_upper_upload',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='right_lower_upload',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='right_upper_upload',
        ),
    ]
