# Generated by Django 4.2.7 on 2024-03-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_patient_left_lower_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_age',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='register_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
