# Generated by Django 4.2.7 on 2024-03-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_patient_patient_age_patient_patient_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='classification',
            field=models.CharField(default='牙科', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='diagnose_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='diagnostic_opinion',
            field=models.CharField(default='等待医生录入', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='handling_opinion',
            field=models.CharField(default='等待医生录入', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='note',
            field=models.CharField(default='等待医生录入', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='visiting_doctor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
